// Generated by web2atomic/tools/bundle-nextgen-arkweb-runtime.mjs.
(() => {
'use strict';
const { WEB_COMPONENT_REGISTRY, componentDefinition, registerWebComponents } = (() => {
const COMPONENTS = Object.freeze([
  Object.freeze({
    component: 'w2a.screen',
    version: 1,
    tagName: 'w2a-screen',
    className: 'w2a-screen',
    variants: Object.freeze(['standard']),
    slots: Object.freeze(['appBar', 'topBar', 'body', 'webView', 'bottomBar']),
    update() {},
  }),
  Object.freeze({
    component: 'w2a.app-bar',
    version: 1,
    tagName: 'w2a-app-bar',
    className: 'w2a-app-bar',
    variants: Object.freeze(['standard', 'searchable']),
    slots: Object.freeze([]),
    update: updateFields([['title', 'span']]),
  }),
  Object.freeze({
    component: 'w2a.shell-toolbar',
    version: 1,
    tagName: 'w2a-shell-toolbar',
    className: 'w2a-shell-toolbar',
    variants: Object.freeze(['standard', 'compact']),
    slots: Object.freeze(['actions']),
    update: updateShellToolbar,
  }),
  Object.freeze({
    component: 'w2a.vertical-feed',
    version: 1,
    tagName: 'w2a-vertical-feed',
    className: 'w2a-vertical-feed',
    variants: Object.freeze(['standard']),
    slots: Object.freeze(['children']),
    update() {},
  }),
  Object.freeze({
    component: 'w2a.navigation-tabs',
    version: 1,
    tagName: 'w2a-navigation-tabs',
    className: 'w2a-navigation-tabs',
    variants: Object.freeze(['scrollable', 'fixed']),
    slots: Object.freeze(['item']),
    update: updateFields([['items', 'span']]),
  }),
  Object.freeze({
    component: 'w2a.notice',
    version: 1,
    tagName: 'w2a-notice',
    className: 'w2a-notice',
    variants: Object.freeze(['standard', 'warning']),
    slots: Object.freeze([]),
    update: updateFields([['title', 'h2'], ['subtitle', 'p'], ['text', 'p'], ['label', 'span']]),
  }),
  Object.freeze({
    component: 'w2a.state-view',
    version: 1,
    tagName: 'w2a-state-view',
    className: 'w2a-state-view',
    variants: Object.freeze(['loading', 'empty', 'error', 'success', 'needs-user']),
    slots: Object.freeze([]),
    update: updateStateView,
  }),
  Object.freeze({
    component: 'w2a.action-grid',
    version: 1,
    tagName: 'w2a-action-grid',
    className: 'w2a-action-grid',
    variants: Object.freeze(['prominent', 'compact']),
    slots: Object.freeze(['item']),
    update: updateFields([['title', 'h2'], ['subtitle', 'p']]),
  }),
  Object.freeze({
    component: 'w2a.action-card',
    version: 1,
    tagName: 'w2a-action-card',
    className: 'w2a-action-card',
    variants: Object.freeze(['prominent', 'compact', 'icon-label']),
    slots: Object.freeze([]),
    update: updateVisualFields([['title', 'h3'], ['subtitle', 'p'], ['label', 'span'], ['meta', 'small']], {
      icon: true,
    }),
  }),
  Object.freeze({
    component: 'w2a.action-button',
    version: 1,
    tagName: 'w2a-action-button',
    className: 'w2a-action-button',
    variants: Object.freeze(['primary', 'secondary', 'quiet']),
    slots: Object.freeze([]),
    update: updateActionButton,
  }),
  Object.freeze({
    component: 'w2a.hero',
    version: 1,
    tagName: 'w2a-hero',
    className: 'w2a-hero',
    variants: Object.freeze(['compact-overlay', 'split', 'text-first']),
    slots: Object.freeze([]),
    update: updateVisualFields([['eyebrow', 'span'], ['title', 'h1'], ['subtitle', 'p'], ['summary', 'p']], {
      image: true,
      eagerImage: true,
    }),
  }),
  Object.freeze({
    component: 'w2a.chip-rail',
    version: 1,
    tagName: 'w2a-chip-rail',
    className: 'w2a-chip-rail',
    variants: Object.freeze(['scrollable']),
    slots: Object.freeze(['item']),
    update: updateFields([['title', 'h2'], ['subtitle', 'p']]),
  }),
  Object.freeze({
    component: 'w2a.navigation-chip',
    version: 1,
    tagName: 'w2a-navigation-chip',
    className: 'w2a-navigation-chip',
    variants: Object.freeze(['standard']),
    slots: Object.freeze([]),
    update: updateFields([['label', 'span'], ['title', 'span']]),
  }),
  Object.freeze({
    component: 'w2a.content-section',
    version: 1,
    tagName: 'w2a-content-section',
    className: 'w2a-content-section',
    variants: Object.freeze(['standard', 'featured', 'compact']),
    slots: Object.freeze(['content']),
    update: updateFields([['title', 'h2'], ['subtitle', 'p']]),
  }),
  Object.freeze({
    component: 'w2a.content-rail',
    version: 1,
    tagName: 'w2a-content-rail',
    className: 'w2a-content-rail',
    variants: Object.freeze(['large', 'compact']),
    slots: Object.freeze(['item']),
    update() {},
  }),
  Object.freeze({
    component: 'w2a.content-list',
    version: 1,
    tagName: 'w2a-content-list',
    className: 'w2a-content-list',
    variants: Object.freeze(['standard', 'compact']),
    slots: Object.freeze(['item']),
    update() {},
  }),
  Object.freeze({
    component: 'w2a.media-card',
    version: 1,
    tagName: 'w2a-media-card',
    className: 'w2a-media-card',
    variants: Object.freeze(['image-top', 'horizontal-compact', 'text-overlay']),
    slots: Object.freeze([]),
    update: updateVisualFields([['title', 'h3'], ['subtitle', 'p'], ['meta', 'small']], { image: true }),
  }),
  Object.freeze({
    component: 'w2a.event-card',
    version: 1,
    tagName: 'w2a-event-card',
    className: 'w2a-event-card',
    variants: Object.freeze(['date-leading', 'image-top']),
    slots: Object.freeze([]),
    update: updateVisualFields([['title', 'h3'], ['date', 'time'], ['subtitle', 'p'], ['meta', 'small']], {
      image: true,
    }),
  }),
  Object.freeze({
    component: 'w2a.article-row',
    version: 1,
    tagName: 'w2a-article-row',
    className: 'w2a-article-row',
    variants: Object.freeze(['thumbnail-leading', 'text-only']),
    slots: Object.freeze([]),
    update: updateVisualFields([['title', 'h3'], ['subtitle', 'p'], ['meta', 'small']], { image: true }),
  }),
  Object.freeze({
    component: 'w2a.bottom-navigation',
    version: 1,
    tagName: 'w2a-bottom-navigation',
    className: 'w2a-bottom-navigation',
    variants: Object.freeze(['icon-label']),
    slots: Object.freeze(['item']),
    update: updateFields([['items', 'span']]),
  }),
  Object.freeze({
    component: 'w2a.webview-route',
    version: 1,
    tagName: 'w2a-webview-route',
    className: 'w2a-webview-surface',
    variants: Object.freeze(['same-shell']),
    slots: Object.freeze([]),
    update(element, node) {
      element.dataset.hostOwned = 'true';
      const label = ensurePart(element, 'placeholder', 'span');
      label.className = 'w2a-webview-placeholder';
      label.textContent = String(node.accessibility?.label || '');
    },
  }),
  Object.freeze({
    component: 'w2a.surface-portal',
    version: 1,
    tagName: 'w2a-surface-portal',
    className: 'w2a-surface-portal',
    variants: Object.freeze(['principal-session', 'external-authority']),
    slots: Object.freeze([]),
    update: updateSurfacePortal,
  }),
]);

const BY_COMPONENT = new Map(COMPONENTS.map((item) => [item.component, item]));

const WEB_COMPONENT_REGISTRY = Object.freeze({
  schemaVersion: 'asrelease-next-web-component-registry/v1',
  registryId: 'web2atomic.next.web-native/v1',
  rendererApi: '1.0',
  composition: 'light-dom',
  components: Object.freeze(COMPONENTS.map(({ component, version, tagName, variants, slots }) =>
    Object.freeze({ component, version, tagName, variants, slots }))),
});

function directChild(element, predicate) {
  return Array.from(element.children).find(predicate) || null;
}

function ensurePart(element, name, tagName) {
  let part = directChild(element, (child) => child.dataset.w2aPart === name);
  if (part && part.localName !== tagName) {
    part.remove();
    part = null;
  }
  if (!part) {
    part = element.ownerDocument.createElement(tagName);
    part.dataset.w2aPart = name;
    element.prepend(part);
  }
  return part;
}

function updateFields(fields) {
  return updateVisualFields(fields);
}

const ICON_PATHS = Object.freeze({
  home: Object.freeze(['M3 10.5 12 3l9 7.5', 'M5 9.5V21h14V9.5', 'M9 21v-7h6v7']),
  ticket: Object.freeze(['M3 7a2 2 0 0 0 0 4v6h18v-6a2 2 0 0 0 0-4V7H3Z', 'M13 7v10']),
  'visit-plan': Object.freeze(['M6 2v4M18 2v4M3 9h18', 'M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2Z']),
  'audio-guide': Object.freeze(['M4 14v-2a8 8 0 0 1 16 0v2', 'M4 14h3v7H5a1 1 0 0 1-1-1v-6ZM20 14h-3v7h2a1 1 0 0 0 1-1v-6Z']),
  'site-map': Object.freeze(['M3 6l6-3 6 3 6-3v15l-6 3-6-3-6 3V6Z', 'M9 3v15M15 6v15']),
  cart: Object.freeze(['M3 3h2l2.4 11.2a2 2 0 0 0 2 1.6h7.9a2 2 0 0 0 2-1.6L21 7H6', 'M10 21h.01M18 21h.01']),
  account: Object.freeze(['M20 21a8 8 0 0 0-16 0', 'M12 13a5 5 0 1 0 0-10 5 5 0 0 0 0 10Z']),
  search: Object.freeze(['M21 21l-4.35-4.35', 'M11 18a7 7 0 1 0 0-14 7 7 0 0 0 0 14Z']),
  refresh: Object.freeze(['M20 6v5h-5', 'M4 18v-5h5', 'M18.5 9A7 7 0 0 0 6.2 6.2L4 11M5.5 15A7 7 0 0 0 17.8 17.8L20 13']),
  destination: Object.freeze(['M12 21s7-5.2 7-12A7 7 0 1 0 5 9c0 6.8 7 12 7 12Z', 'M12 11.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z']),
  default: Object.freeze(['M5 12h14', 'M13 6l6 6-6 6']),
});

function ensureIcon(element, role) {
  let icon = directChild(element, (child) => child.dataset.w2aPart === 'icon');
  if (icon && icon.namespaceURI !== 'http://www.w3.org/2000/svg') {
    icon.remove();
    icon = null;
  }
  if (!icon) {
    icon = element.ownerDocument.createElementNS('http://www.w3.org/2000/svg', 'svg');
    icon.dataset.w2aPart = 'icon';
    element.prepend(icon);
  }
  icon.setAttribute('viewBox', '0 0 24 24');
  icon.setAttribute('fill', 'none');
  icon.setAttribute('stroke', 'currentColor');
  icon.setAttribute('stroke-width', '1.8');
  icon.setAttribute('stroke-linecap', 'round');
  icon.setAttribute('stroke-linejoin', 'round');
  icon.setAttribute('aria-hidden', 'true');
  icon.setAttribute('focusable', 'false');
  icon.dataset.iconRole = role;
  const namespace = 'http://www.w3.org/2000/svg';
  const paths = ICON_PATHS[role] || ICON_PATHS.default;
  icon.replaceChildren(...paths.map((data) => {
    const path = element.ownerDocument.createElementNS(namespace, 'path');
    path.setAttribute('d', data);
    return path;
  }));
  return icon;
}

function updateVisualFields(fields, options = {}) {
  return (element, node) => {
    const desired = [];
    if (options.image && node.content?.image) {
      const image = ensurePart(element, 'image', 'img');
      image.src = String(node.content.image);
      image.alt = '';
      image.decoding = 'async';
      image.loading = options.eagerImage ? 'eager' : 'lazy';
      desired.push(image);
    }
    const iconRole = String(node.content?.icon || node.props?.iconRole || '');
    if (options.icon && iconRole) desired.push(ensureIcon(element, iconRole));
    for (const [name, tagName] of fields) {
      const value = node.content?.[name];
      if (value === undefined || value === null || value === '') continue;
      const part = ensurePart(element, name, tagName);
      part.textContent = String(value);
      desired.push(part);
    }
    const keep = new Set(desired);
    for (const child of Array.from(element.children)) {
      if (child.dataset.w2aPart && !keep.has(child)) child.remove();
    }
    for (const child of desired) element.append(child);
  };
}

function updateStateView(element, node) {
  updateFields([['title', 'h2'], ['subtitle', 'p']])(element, node);
  const liveRegion = String(node.props?.liveRegion || (node.variant === 'error' ? 'assertive' : 'polite'));
  if (!['off', 'polite', 'assertive'].includes(liveRegion)) {
    throw new Error(`invalid state-view live region for ${node.id}`);
  }
  element.setAttribute('aria-live', liveRegion);
  element.dataset.state = node.variant;
}

function updateActionButton(element, node) {
  const control = ensurePart(element, 'control', 'button');
  control.type = 'button';
  control.textContent = String(node.content?.label || node.accessibility?.label || '');
  control.disabled = !node.action;
  const subtitle = node.content?.subtitle;
  if (subtitle) {
    const detail = ensurePart(element, 'subtitle', 'small');
    detail.textContent = String(subtitle);
    element.append(control, detail);
  } else {
    for (const child of Array.from(element.children)) {
      if (child.dataset.w2aPart === 'subtitle') child.remove();
    }
    element.append(control);
  }
}

function updateShellToolbar(element, node) {
  updateFields([['title', 'span']])(element, node);
  const density = String(node.props?.density || (node.variant === 'compact' ? 'compact' : 'comfortable'));
  if (!['compact', 'comfortable'].includes(density)) {
    throw new Error(`invalid shell-toolbar density for ${node.id}`);
  }
  element.dataset.density = density;
  element.dataset.sticky = String(node.props?.sticky !== false);
}

function updateSurfacePortal(element, node) {
  const surfaceKind = String(node.props?.surfaceKind || '');
  const expectedKind = node.variant === 'external-authority'
    ? 'external-authority-webview' : 'principal-session-webview';
  if (surfaceKind !== expectedKind) {
    throw new Error(`surface portal kind drifted for ${node.id}: ${surfaceKind}`);
  }
  const surfaceRef = String(node.content?.surfaceRef || '');
  if (!/^[a-z][a-z0-9.-]{1,127}$/.test(surfaceRef)) {
    throw new Error(`surface portal reference is invalid for ${node.id}`);
  }
  element.dataset.hostOwned = 'true';
  element.dataset.surfaceKind = surfaceKind;
  element.dataset.surfaceRef = surfaceRef;
  const label = ensurePart(element, 'placeholder', 'span');
  label.className = 'w2a-surface-portal-placeholder';
  label.textContent = String(node.content?.label || node.accessibility?.label || '');
}

function configureAction(element, node) {
  element.__w2aAction = node.action || null;
  if (!element.__w2aActionBound) {
    const dispatch = (event) => {
      const origin = event.composedPath().find((item) => item?.dataset?.nodeId);
      if (origin !== element || !element.__w2aAction) return;
      if (event.type === 'keydown' && event.target?.localName === 'button') return;
      const root = element.ownerDocument.defaultView || globalThis;
      element.dispatchEvent(new root.CustomEvent('w2a-action', {
        bubbles: true,
        composed: true,
        detail: {
          nodeId: element.dataset.nodeId,
          component: element.dataset.component,
          action: { ...element.__w2aAction },
        },
      }));
    };
    element.addEventListener('click', dispatch);
    element.addEventListener('keydown', (event) => {
      if (event.key === 'Enter' || event.key === ' ') dispatch(event);
    });
    element.__w2aActionBound = true;
  }
  const nativeControl = directChild(element, (child) => child.dataset.w2aPart === 'control');
  if (node.action) {
    if (nativeControl) {
      element.removeAttribute('tabindex');
      nativeControl.disabled = false;
    } else {
      element.tabIndex = 0;
    }
    element.dataset.actionKind = node.action.kind;
    element.dataset.actionTarget = node.action.target;
  } else {
    element.removeAttribute('tabindex');
    if (nativeControl) nativeControl.disabled = true;
    delete element.dataset.actionKind;
    delete element.dataset.actionTarget;
  }
}

function applyContract(element, definition, node) {
  if (node.component !== definition.component || node.version !== definition.version) {
    throw new Error(`Web Component contract mismatch for ${node.id}`);
  }
  if (!definition.variants.includes(node.variant)) {
    throw new Error(`Web Component variant mismatch for ${node.id}: ${node.variant}`);
  }
  element.className = definition.className;
  element.dataset.nodeId = node.id;
  element.dataset.component = node.component;
  element.dataset.componentVersion = String(node.version);
  element.dataset.variant = node.variant;
  const emphasis = String(node.props?.emphasis || 'standard');
  element.dataset.emphasis = emphasis;
  const compactColumns = Number(node.props?.columnsCompact);
  const expandedColumns = Number(node.props?.columnsExpanded);
  if (Number.isInteger(compactColumns) && compactColumns >= 1 && compactColumns <= 6) {
    element.style.setProperty('--w2a-columns-compact', String(compactColumns));
  } else {
    element.style.removeProperty('--w2a-columns-compact');
  }
  if (Number.isInteger(expandedColumns) && expandedColumns >= 1 && expandedColumns <= 6) {
    element.style.setProperty('--w2a-columns-expanded', String(expandedColumns));
  } else {
    element.style.removeProperty('--w2a-columns-expanded');
  }
  element.setAttribute('role', node.accessibility.role);
  element.setAttribute('aria-label', node.accessibility.label);
  definition.update(element, node);
  configureAction(element, node);
}

function componentDefinition(component) {
  return BY_COMPONENT.get(component) || null;
}

function registerWebComponents(root = globalThis) {
  const customElements = root.customElements;
  const HTMLElement = root.HTMLElement;
  if (!customElements || typeof customElements.define !== 'function' || typeof HTMLElement !== 'function') {
    throw new Error('Web Component registry requires CustomElementRegistry and HTMLElement');
  }

  const registered = [];
  for (const definition of COMPONENTS) {
    const existing = customElements.get(definition.tagName);
    if (!existing) {
      customElements.define(definition.tagName, class extends HTMLElement {
        applyRenderNode(node) {
          applyContract(this, definition, node);
        }
      });
    }
    registered.push({
      component: definition.component,
      version: definition.version,
      tagName: definition.tagName,
      variants: definition.variants,
      slots: definition.slots,
      reusedDefinition: Boolean(existing),
    });
  }

  return {
    status: 'OK',
    schemaVersion: WEB_COMPONENT_REGISTRY.schemaVersion,
    registryId: WEB_COMPONENT_REGISTRY.registryId,
    rendererApi: WEB_COMPONENT_REGISTRY.rendererApi,
    composition: WEB_COMPONENT_REGISTRY.composition,
    registered,
  };
}
return { WEB_COMPONENT_REGISTRY, componentDefinition, registerWebComponents };
})();

const { renderResolvedModel, applyRendererUpdatePlan } = (() => {
function applyTheme(document, theme) {
  const style = document.documentElement.style;
  style.setProperty('--w2a-surface', theme.surface);
  style.setProperty('--w2a-surface-raised', theme.surfaceRaised);
  style.setProperty('--w2a-text', theme.text);
  style.setProperty('--w2a-text-muted', theme.textMuted);
  style.setProperty('--w2a-accent', theme.accent);
  style.setProperty('--w2a-accent-strong', theme.accentStrong);
}

function directSlot(element, slotName) {
  return Array.from(element.children).find((child) => child.dataset.slot === slotName) || null;
}

function reconcileChildren(parent, desired) {
  const keep = new Set(desired);
  for (const child of desired) parent.append(child);
  for (const child of Array.from(parent.children)) {
    if (!keep.has(child)) child.remove();
  }
}

function placement(element) {
  const slot = element.parentElement;
  const owner = slot?.parentElement;
  const siblings = slot
    ? Array.from(slot.children).filter((child) => child.dataset.nodeId)
    : [];
  return {
    parentNodeId: owner?.dataset.nodeId || '$root',
    slot: slot?.dataset.slot || '$root',
    index: siblings.indexOf(element),
  };
}

function propIdList(value) {
  if (Array.isArray(value)) return value.map(String);
  if (typeof value !== 'string' || !value) return [];
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) ? parsed.map(String) : [];
  } catch {
    return [];
  }
}

function collectionItemMatches(nodeId, itemId) {
  return nodeId === itemId || nodeId.endsWith(`.${itemId}`);
}

function applyCollectionPresentation(parentNode, childNodes) {
  const activeIds = propIdList(parentNode.props?.activeItemIds);
  const emphasizedIds = propIdList(parentNode.props?.emphasizedItemIds);
  childNodes.forEach((child, index) => {
    child.dataset.collectionIndex = String(index);
    child.dataset.active = String(activeIds.some((itemId) =>
      collectionItemMatches(child.dataset.nodeId, itemId)));
    child.dataset.emphasized = String(emphasizedIds.some((itemId) =>
      collectionItemMatches(child.dataset.nodeId, itemId)));
  });
}

function renderNode(document, node, context) {
  if (!node?.id || context.visited.has(node.id)) {
    throw new Error(`invalid or duplicate RenderModel node id: ${node?.id}`);
  }
  context.visited.add(node.id);

  const definition = componentDefinition(node.component);
  if (!definition || definition.version !== node.version) {
    throw new Error(`Web Component registry does not support ${node.component}@${node.version}`);
  }

  let element = context.existing.get(node.id) || null;
  if (element && (
    element.localName !== definition.tagName ||
    element.dataset.component !== node.component ||
    element.dataset.componentVersion !== String(node.version)
  )) {
    context.replaced.push(node.id);
    element = null;
  }
  if (element) {
    context.reused.push(node.id);
  } else {
    element = document.createElement(definition.tagName);
    context.created.push(node.id);
  }
  if (typeof element.applyRenderNode !== 'function') {
    throw new Error(`custom element ${definition.tagName} is not registered`);
  }
  element.applyRenderNode(node);

  const desiredSlots = [];
  const suppliedSlots = Object.keys(node.slots || {});
  const unknownSlot = suppliedSlots.find((slotName) => !definition.slots.includes(slotName));
  if (unknownSlot) {
    throw new Error(`${node.component}@${node.version} does not admit slot ${unknownSlot}`);
  }
  for (const slotName of definition.slots) {
    const child = node.slots?.[slotName];
    if (child === undefined || child === null) continue;
    let slot = directSlot(element, slotName);
    if (!slot) {
      slot = document.createElement('div');
      slot.dataset.slot = slotName;
    }
    slot.className = `w2a-slot w2a-slot-${slotName}`;
    const childNodes = (Array.isArray(child) ? child : [child])
      .filter(Boolean)
      .map((item) => renderNode(document, item, context));
    applyCollectionPresentation(node, childNodes);
    reconcileChildren(slot, childNodes);
    desiredSlots.push(slot);
  }

  const parts = Array.from(element.children).filter((child) => child.dataset.w2aPart);
  reconcileChildren(element, [...parts, ...desiredSlots]);
  return element;
}

function renderResolvedModel(model, { document = globalThis.document, target } = {}) {
  if (!document || !target) throw new Error('document and target are required');
  if (model?.schemaVersion !== 'asrelease-render-model/v1') throw new Error('unsupported RenderModel schema');
  if (model.rendererApi !== WEB_COMPONENT_REGISTRY.rendererApi) throw new Error('unsupported Renderer API');

  applyTheme(document, model.theme);
  const registry = registerWebComponents(document.defaultView || globalThis);
  const existingNodes = Array.from(target.querySelectorAll('[data-node-id]'));
  if (new Set(existingNodes.map((element) => element.dataset.nodeId)).size !== existingNodes.length) {
    throw new Error('existing Web Component tree contains duplicate node IDs');
  }
  const existingIds = new Set(existingNodes.map((element) => element.dataset.nodeId));
  const previousPlacements = new Map(existingNodes.map((element) => [element.dataset.nodeId, placement(element)]));
  const context = {
    existing: new Map(existingNodes.map((element) => [element.dataset.nodeId, element])),
    visited: new Set(),
    created: [],
    reused: [],
    replaced: [],
  };
  const root = renderNode(document, model.root, context);
  reconcileChildren(target, [root]);

  const nodes = Array.from(target.querySelectorAll('[data-node-id]'));
  const slotNames = Array.from(target.querySelectorAll('[data-slot]')).map((item) => item.dataset.slot);
  const removedNodeIds = existingNodes
    .map((element) => element.dataset.nodeId)
    .filter((nodeId) => !context.visited.has(nodeId));
  const insertedNodeIds = context.created.filter((nodeId) => !existingIds.has(nodeId));
  const movedNodeIds = context.reused.filter((nodeId) => {
    const before = previousPlacements.get(nodeId);
    const element = nodes.find((item) => item.dataset.nodeId === nodeId);
    return element && JSON.stringify(before) !== JSON.stringify(placement(element));
  });
  const surfacePortals = Array.from(target.querySelectorAll('w2a-surface-portal')).map((element) => ({
    nodeId: element.dataset.nodeId,
    surfaceKind: element.dataset.surfaceKind,
    surfaceRef: element.dataset.surfaceRef,
    hostOwned: element.dataset.hostOwned === 'true',
  }));
  const hostSurfaces = Array.from(target.querySelectorAll('w2a-webview-route, w2a-surface-portal'));
  const receipt = {
    status: 'OK',
    schemaVersion: 'asrelease-next-web-component-renderer-receipt/v1',
    modelRevision: model.revision,
    semanticBackend: 'web-components-light-dom',
    renderStrategy: 'keyed-incremental',
    registry,
    nodeIds: nodes.map((item) => item.dataset.nodeId),
    componentTags: nodes.map((item) => `${item.dataset.component}@${item.dataset.componentVersion}=${item.localName}`),
    accessibilityLabels: nodes.map((item) => item.getAttribute('aria-label')),
    slots: slotNames,
    createdNodeIds: context.created,
    insertedNodeIds,
    reusedNodeIds: context.reused,
    removedNodeIds,
    movedNodeIds,
    replacedNodeIds: context.replaced,
    merchantNavigationVisible: slotNames.includes('topBar') || slotNames.includes('bottomBar'),
    webViewHostOwned: hostSurfaces.length > 0 &&
      hostSurfaces.every((element) => element.dataset.hostOwned === 'true'),
    surfacePortals,
  };
  target.__w2aRenderReceipt = receipt;
  return receipt;
}

function applyRendererUpdatePlan(plan, options = {}) {
  if (plan?.schemaVersion !== 'asrelease-renderer-update-plan/v1') {
    throw new Error('unsupported Renderer update plan');
  }
  if (plan.rendererProfileId !== 'web-native') {
    throw new Error('Web Component Renderer profile is not admitted');
  }
  if (plan.effectExecuted !== false || !['mount', 'patch'].includes(plan.mode)) {
    throw new Error('Renderer update plan authority is invalid');
  }
  if (!Array.isArray(plan.operations) || plan.operations.length !== plan.operationCount) {
    throw new Error('Renderer update plan operation count drifted');
  }
  const admittedOperations = new Set([
    'insert', 'remove', 'move', 'replace', 'update', 'theme', 'viewport',
  ]);
  if (plan.operations.some((operation) => !admittedOperations.has(operation?.op))) {
    throw new Error('Renderer update plan operation is not admitted');
  }
  const model = plan.nextModel;
  if (model?.revision !== plan.modelRevision) {
    throw new Error('Renderer update plan model revision drifted');
  }
  const rendererReceipt = renderResolvedModel(model, options);
  if (rendererReceipt.nodeIds.length !== plan.nodeCount) {
    throw new Error('Renderer update plan node count drifted');
  }
  return {
    status: 'APPLIED',
    schemaVersion: 'asrelease-renderer-applied-receipt/v1',
    planId: plan.planId,
    rendererProfileId: plan.rendererProfileId,
    modelRevision: plan.modelRevision,
    semanticBackend: rendererReceipt.semanticBackend,
    appliedOperationCount: plan.operationCount,
    renderedNodeCount: rendererReceipt.nodeIds.length,
    surfacePortals: rendererReceipt.surfacePortals,
    rendererReceipt,
    effectExecuted: false,
  };
}
return { renderResolvedModel, applyRendererUpdatePlan };
})();

const BRIDGE_SCHEMA = 'asrelease-next-native-surface-bridge-message/v1';
const MAX_BRIDGE_BYTES = 65536;
const HOST_KINDS = new Set([
  'host.publish-plan',
  'host.publish-portal-state',
  'host.publish-lifecycle',
  'host.navigate-home',
]);
const FORBIDDEN_KEYS = new Set([
  'controller', 'selector', 'cookie', 'credential', 'password', 'token',
  'privateResponse', 'formValue',
]);

let port = null;
let outboundSequence = 0;
let inboundSequence = 0;
let currentModelRevision = '';
const target = document.getElementById('target');
const status = document.getElementById('status');

function containsForbiddenKey(value) {
  if (!value || typeof value !== 'object') return false;
  if (Array.isArray(value)) return value.some(containsForbiddenKey);
  return Object.entries(value).some(([key, item]) =>
    FORBIDDEN_KEYS.has(key) || containsForbiddenKey(item));
}

function parseHostMessage(raw) {
  if (typeof raw !== 'string' || new TextEncoder().encode(raw).byteLength > MAX_BRIDGE_BYTES) {
    throw new Error('bridge message exceeds byte limit');
  }
  const message = JSON.parse(raw);
  if (message?.schemaVersion !== BRIDGE_SCHEMA || !HOST_KINDS.has(message.kind)) {
    throw new Error('bridge message is not admitted');
  }
  if (!Number.isSafeInteger(message.sequence) || message.sequence <= inboundSequence) {
    throw new Error('bridge sequence is stale');
  }
  if (containsForbiddenKey(message.payload)) throw new Error('bridge payload contains forbidden key');
  inboundSequence = message.sequence;
  return message;
}

function post(kind, payload) {
  if (!port) return;
  const raw = JSON.stringify({
    schemaVersion: BRIDGE_SCHEMA,
    kind,
    sequence: ++outboundSequence,
    payload,
  });
  if (new TextEncoder().encode(raw).byteLength > MAX_BRIDGE_BYTES) {
    throw new Error('presentation bridge response exceeds byte limit');
  }
  port.postMessage(raw);
}

function publishPortalLayouts(receipt) {
  for (const portal of receipt.surfacePortals || []) {
    const element = Array.from(target.querySelectorAll('[data-node-id]'))
      .find((candidate) => candidate.dataset.nodeId === portal.nodeId);
    const bounds = element?.getBoundingClientRect();
    if (!bounds) continue;
    post('presentation.portal-layout-request', {
      modelRevision: currentModelRevision,
      nodeId: portal.nodeId,
      surfaceKind: portal.surfaceKind,
      surfaceRef: portal.surfaceRef,
      viewport: { width: innerWidth, height: innerHeight },
      bounds: { x: bounds.x, y: bounds.y, width: bounds.width, height: bounds.height },
    });
  }
}

function receive(raw) {
  try {
    const message = parseHostMessage(raw);
    if (message.kind === 'host.publish-plan') {
      const plan = message.payload?.plan;
      currentModelRevision = String(plan?.modelRevision || '');
      const receipt = applyRendererUpdatePlan(plan, { document, target });
      status.textContent = `rendered:${receipt.renderedNodeCount}`;
      post('presentation.render-receipt', receipt);
      publishPortalLayouts(receipt.rendererReceipt);
    } else if (message.kind === 'host.publish-portal-state') {
      document.documentElement.dataset.portalState = String(message.payload?.state || 'unknown');
    } else if (message.kind === 'host.publish-lifecycle') {
      document.documentElement.dataset.lifecycle = String(message.payload?.state || 'unknown');
    } else {
      globalThis.scrollTo(0, 0);
      document.documentElement.dataset.nativeRoute = 'home';
      document.documentElement.dataset.homeSequence = String(message.sequence);
    }
  } catch (error) {
    status.textContent = `bridge-fail:${String(error.message || error)}`;
  }
}

target.addEventListener('w2a-action', (event) => {
  post('presentation.action-request', {
    modelRevision: currentModelRevision,
    nodeId: event.detail?.nodeId,
    effectExecuted: false,
  });
});

globalThis.addEventListener('message', (event) => {
  if (event.data !== '__w2a_native_surface_bridge__' || event.ports?.length !== 1 || port) return;
  port = event.ports[0];
  port.onmessage = (message) => receive(message.data);
  port.start?.();
  registerWebComponents(globalThis);
  status.textContent = `ready:${WEB_COMPONENT_REGISTRY.components.length}`;
  post('presentation.ready', {
    registryId: WEB_COMPONENT_REGISTRY.registryId,
    rendererApi: WEB_COMPONENT_REGISTRY.rendererApi,
    components: WEB_COMPONENT_REGISTRY.components.length,
    websiteSessionOwned: false,
  });
});
})();
