// Generated by web2atomic/tools/bundle-nextgen-arkweb-runtime.mjs.
(() => {
'use strict';
const { selectWebsiteProfile } = (() => {
const PROFILE_SCHEMA = 'asrelease-website-experience-profile/v1';
const RECEIPT_SCHEMA = 'asrelease-next-website-profile-selection-receipt/v1';
const REVISION = /^[a-f0-9]{64}$/;

function requireValue(condition, message) {
  if (!condition) throw new Error(message);
}

function normalizeOrigin(url) {
  const parsed = new URL(url);
  requireValue(parsed.protocol === 'https:', 'website profile observation must use HTTPS');
  requireValue(!parsed.username && !parsed.password, 'website profile URL cannot contain credentials');
  return { origin: parsed.origin, path: parsed.pathname || '/' };
}

function validateIntegrity(profile, nowEpochMs) {
  const source = profile.source || {};
  const integrity = profile.integrity || {};
  requireValue(['embedded', 'cloud', 'platform-release'].includes(source.mode),
    'website profile source mode is unsupported');
  requireValue(integrity.status === 'verified', 'website profile integrity is not verified');
  requireValue(REVISION.test(String(integrity.digest || '')), 'website profile digest is invalid');
  if (source.mode === 'embedded') {
    requireValue(integrity.authority === 'hap-signed-resource', 'embedded profile integrity authority drifted');
  } else if (source.mode === 'cloud') {
    requireValue(integrity.authority === 'native-host-digest-and-signature-verifier',
      'cloud profile integrity authority drifted');
    requireValue(integrity.signatureStatus === 'verified' && typeof integrity.signerKeyId === 'string' && integrity.signerKeyId,
      'cloud profile signature is not verified');
    requireValue(Number.isSafeInteger(source.expiresAtEpochMs) && source.expiresAtEpochMs >= nowEpochMs,
      'cloud profile is expired');
  } else {
    requireValue(integrity.authority === 'native-host-platform-release-verifier',
      'platform release profile integrity authority drifted');
  }
}

function sourcePriority(mode) {
  return { embedded: 0, cloud: 1, 'platform-release': 2 }[mode] ?? -1;
}

function inspectCandidate(profile, observation, host, nowEpochMs) {
  requireValue(profile?.schemaVersion === PROFILE_SCHEMA, 'website profile schema is unsupported');
  const identity = profile.identity || {};
  requireValue(typeof identity.profileId === 'string' && identity.profileId,
    'website profile identity is missing');
  requireValue(Number.isSafeInteger(identity.generation) && identity.generation > 0,
    'website profile generation is invalid');
  requireValue(REVISION.test(String(identity.revision || '')), 'website profile revision is invalid');
  validateIntegrity(profile, nowEpochMs);
  requireValue(profile.runtime?.hostApi === host.hostApi, 'website profile Host API is incompatible');
  requireValue(profile.runtime?.rendererApi === host.rendererApi, 'website profile Renderer API is incompatible');

  const location = normalizeOrigin(observation.url);
  const match = profile.match || {};
  const originMatch = Array.isArray(match.origins) && match.origins.includes(location.origin);
  const routeMatch = Array.isArray(match.routePrefixes) && match.routePrefixes.some((prefix) =>
    typeof prefix === 'string' && prefix.startsWith('/') && location.path.startsWith(prefix));
  if (!originMatch || !routeMatch) return null;

  const requiredSignals = Array.isArray(match.semanticSignals) ? match.semanticSignals : [];
  const observedSignals = new Set(Array.isArray(observation.semanticSignals) ? observation.semanticSignals : []);
  const matchedSignals = requiredSignals.filter((signal) => observedSignals.has(signal));
  requireValue(Number.isSafeInteger(match.minimumSignals) && match.minimumSignals > 0 &&
    match.minimumSignals <= requiredSignals.length, 'website profile semantic threshold is invalid');
  if (matchedSignals.length < match.minimumSignals) return null;
  return {
    profile,
    matchStatus: matchedSignals.length === requiredSignals.length ? 'exact' : 'compatible',
    matchedSignals: matchedSignals.length,
  };
}

function chooseTarget(profile, requestedTarget, host) {
  requireValue(requestedTarget === 'native-webview-web-native' || requestedTarget === 'native-arkui',
    'website profile target is unsupported');
  const required = profile.projection?.requiredComponents || [];
  requireValue(Array.isArray(required) && required.every((value) => typeof value === 'string'),
    'website profile component requirements are invalid');
  const webComponents = new Set(host.webNativeComponents || []);
  const webMissing = required.filter((component) => !webComponents.has(component));
  requireValue(webMissing.length === 0, `Web-native profile is missing components: ${webMissing.join(',')}`);
  if (requestedTarget === 'native-webview-web-native') {
    return { selectedTarget: requestedTarget, unsupportedComponents: [] };
  }
  const arkUiComponents = new Set(host.arkUiComponents || []);
  const unsupportedComponents = required.filter((component) => !arkUiComponents.has(component));
  return unsupportedComponents.length === 0
    ? { selectedTarget: 'native-arkui', unsupportedComponents }
    : {
        selectedTarget: 'native-webview-web-native',
        targetFallbackReason: 'arkui-component-subset-miss',
        unsupportedComponents,
      };
}

function selectWebsiteProfile({ contract, profiles, observation, requestedTarget, host, nowEpochMs }) {
  requireValue(contract?.schemaVersion === 'asrelease-next-website-profiler-contract/v1',
    'website profiler contract is unsupported');
  requireValue(contract?.output?.schemaVersion === PROFILE_SCHEMA, 'website profiler output schema drifted');
  const accepted = [];
  const rejectedCandidates = [];
  for (const profile of profiles || []) {
    try {
      const candidate = inspectCandidate(profile, observation, host, nowEpochMs);
      if (candidate) accepted.push(candidate);
    } catch (_) {
      const profileId = profile?.identity?.profileId;
      if (typeof profileId === 'string' && profileId) rejectedCandidates.push(profileId);
    }
  }
  accepted.sort((left, right) => {
    const generation = right.profile.identity.generation - left.profile.identity.generation;
    if (generation !== 0) return generation;
    return sourcePriority(right.profile.source.mode) - sourcePriority(left.profile.source.mode);
  });
  if (accepted.length === 0) {
    return {
      status: 'NEEDS_PROFILER',
      schemaVersion: RECEIPT_SCHEMA,
      matchStatus: 'needs-profiler',
      fallbackSurface: contract.selection.unknownFallback,
      rejectedCandidates,
      effectExecuted: false,
    };
  }
  const selected = accepted[0];
  const target = chooseTarget(selected.profile, requestedTarget, host);
  return {
    status: 'SELECTED',
    schemaVersion: RECEIPT_SCHEMA,
    matchStatus: selected.matchStatus,
    profileId: selected.profile.identity.profileId,
    websiteSkillId: selected.profile.identity.websiteSkillId,
    profileGeneration: selected.profile.identity.generation,
    profileRevision: selected.profile.identity.revision,
    profileDigest: selected.profile.integrity.digest,
    profileSource: selected.profile.source.mode,
    selectedTarget: target.selectedTarget,
    targetFallbackReason: target.targetFallbackReason,
    unsupportedComponents: target.unsupportedComponents,
    profilerRefreshRecommended: selected.matchStatus === 'compatible',
    appRebuildRequired: false,
    rejectedCandidates,
    effectExecuted: false,
  };
}
return { selectWebsiteProfile };
})();

const { mapWebViewWebNativeTarget, verifyWebViewWebNativeRendering } = (() => {
const PROFILE_SCHEMA = 'asrelease-next-webview-web-native-profile/v1';
const PLAN_SCHEMA = 'asrelease-next-webview-web-native-target-plan/v1';
const RECEIPT_SCHEMA = 'asrelease-next-webview-web-native-mapping-receipt/v1';

function requireValue(condition, message) {
  if (!condition) throw new Error(message);
}

function validateProfile(profile) {
  requireValue(profile?.schemaVersion === PROFILE_SCHEMA, 'unsupported WebView Web-native profile');
  const target = profile.target || {};
  requireValue(target.id === 'native-webview-web-native', 'WebView Web-native target ID drifted');
  requireValue(target.hostProfile === 'harmony-native-surface-host', 'WebView Web-native Host profile drifted');
  requireValue(target.rendererBackend === 'web-native', 'WebView Web-native Renderer backend drifted');
  requireValue(target.carrier === 'arkweb-webview', 'WebView Web-native carrier drifted');
  requireValue(target.registryId === 'web2atomic.next.web-native/v1', 'WebView Web-native registry drifted');
  requireValue(profile.componentMapping?.default === 'optimized-presentation-webview-dom',
    'WebView Web-native default component mapping drifted');
  requireValue(profile.componentMapping?.['w2a.webview-route'] === 'host-owned-route-surface-portal',
    'WebView route component mapping drifted');
  requireValue(profile.componentMapping?.['w2a.surface-portal'] === 'host-owned-typed-surface-portal',
    'typed surface portal component mapping drifted');
  requireValue(profile.surfaceCoordinator?.coordinatorId === 'harmony-native-surface-coordinator/v1',
    'WebView Web-native surface coordinator drifted');
  requireValue(profile.surfaceCoordinator?.maxSurfaces === 5 &&
    profile.surfaceCoordinator?.maxPortalDepth === 2,
  'WebView Web-native surface coordinator limits drifted');
  requireValue(profile.bridge?.transport === 'WebMessagePort<string>' &&
    profile.bridge?.maxMessageBytes === 65536,
  'WebView Web-native bridge envelope drifted');
  const kinds = new Set((profile.surfaceKinds || []).map((item) => item.id));
  for (const kind of [
    'optimized-presentation-webview',
    'source-execution-webview',
    'principal-session-webview',
    'external-authority-webview',
    'arkui-surface',
  ]) requireValue(kinds.has(kind), `WebView Web-native surface kind is missing: ${kind}`);
  for (const rule of [
    'reuseExactWebComponentRegistry',
    'presentationWebViewLoadsNoRealWebsite',
    'presentationWebViewOwnsNoWebsiteSession',
    'webViewRouteIsPortalNotNestedFrame',
    'surfacePortalUsesOpaqueHostReference',
    'portalActivationIsHostStateNotRenderModelState',
    'rendererOwnsNoWebViewController',
    'rendererExecutesNoEffect',
    'externalAuthoritySurfaceIsOpaque',
    'sourceExecutionSurfaceIsNeverPresented',
    'onlyOnePortalSurfaceIsFocused',
    'underlayPortalSurfacesAreNonInteractive',
    'parkedSurfacesAreOffViewportNoHitTestNoAccessibility',
    'controllerDetachReturnsUncertain',
    'memoryPressureDoesNotDestroyGatewayWorkers',
    'signedArkWebAndDeviceAcceptanceRemainRequired',
  ]) requireValue(profile.rules?.[rule] === true, `WebView Web-native rule drifted: ${rule}`);
}

function collectNodes(node, nodes = []) {
  requireValue(node && typeof node === 'object' && !Array.isArray(node), 'WebView Web-native node must be an object');
  nodes.push(node);
  for (const child of Object.values(node.slots || {})) {
    for (const item of Array.isArray(child) ? child : [child]) collectNodes(item, nodes);
  }
  return nodes;
}

function portalFor(node) {
  if (node.component === 'w2a.surface-portal') {
    const surfaceKind = node.props?.surfaceKind;
    const expectedKind = node.variant === 'external-authority'
      ? 'external-authority-webview' : 'principal-session-webview';
    requireValue(surfaceKind === expectedKind, `WebView Web-native surface portal kind drifted: ${node.id}`);
    const surfaceRef = node.content?.surfaceRef;
    requireValue(typeof surfaceRef === 'string' && /^[a-z][a-z0-9.-]{1,127}$/.test(surfaceRef),
      `WebView Web-native surface portal reference is invalid: ${node.id}`);
    return {
      portalId: `portal.${node.id}`,
      nodeId: node.id,
      component: node.component,
      surfaceRef,
      surfaceKind,
      composition: 'host-owned-native-sibling-surface',
      activation: 'host-state-required',
      opaque: surfaceKind === 'external-authority-webview',
      rendererOwnsController: false,
      effectExecuted: false,
    };
  }
  const url = node.content?.url;
  requireValue(typeof url === 'string' && url.startsWith('https://'),
    `WebView Web-native portal requires an HTTPS route: ${node.id}`);
  return {
    portalId: `portal.${node.id}`,
    nodeId: node.id,
    component: node.component,
    routeUrl: url,
    surfaceKind: 'principal-session-webview',
    composition: 'host-owned-native-sibling-surface',
    activation: 'host-state-required',
    rendererOwnsController: false,
    effectExecuted: false,
  };
}

function mapWebViewWebNativeTarget({ profile, model, resolutionReceipt }) {
  validateProfile(profile);
  requireValue(model?.schemaVersion === 'asrelease-render-model/v1', 'unsupported RenderModel for WebView Web-native');
  requireValue(model.rendererApi === profile.target.rendererApi, 'WebView Web-native Renderer API drifted');
  requireValue(resolutionReceipt?.schemaVersion === 'asrelease-next-website-runtime-target-resolution/v1',
    'WebView Web-native requires a Website Runtime resolution receipt');
  requireValue(resolutionReceipt.modelRevision === model.revision, 'WebView Web-native resolution revision drifted');
  requireValue(resolutionReceipt.rendererOwnsEffects === false, 'WebView Web-native resolution moved effects into Renderer');
  const nodes = collectNodes(model.root);
  requireValue(nodes.length === resolutionReceipt.nodeCount, 'WebView Web-native node count drifted');
  const portals = nodes.filter((node) =>
    node.component === 'w2a.webview-route' || node.component === 'w2a.surface-portal').map(portalFor);
  requireValue(portals.length > 0, 'WebView Web-native target requires at least one Host WebView portal');
  return {
    status: 'MAPPED',
    schemaVersion: PLAN_SCHEMA,
    profileId: profile.profileId,
    targetId: profile.target.id,
    hostProfile: profile.target.hostProfile,
    rendererBackend: profile.target.rendererBackend,
    carrier: profile.target.carrier,
    registryId: profile.target.registryId,
    modelRevision: model.revision,
    nodeCount: nodes.length,
    optimizedUiNodeCount: nodes.length - portals.length,
    hostPortalCount: portals.length,
    portals,
    presentationSurface: {
      kind: 'optimized-presentation-webview',
      content: 'embedded-versioned-web-components',
      websiteSessionOwned: false,
    },
    sourceWorkersEmbeddedInPresentation: false,
    rendererOwnsEffects: false,
    deviceAcceptanceRequired: true,
  };
}

function verifyWebViewWebNativeRendering(plan, rendererReceipt) {
  requireValue(plan?.schemaVersion === PLAN_SCHEMA, 'unsupported WebView Web-native target plan');
  requireValue(rendererReceipt?.schemaVersion === 'asrelease-next-web-component-renderer-receipt/v1',
    'WebView Web-native requires a Web Component renderer receipt');
  requireValue(rendererReceipt.modelRevision === plan.modelRevision, 'WebView Web-native renderer revision drifted');
  requireValue(rendererReceipt.registry?.registryId === plan.registryId, 'WebView Web-native registry receipt drifted');
  requireValue(rendererReceipt.nodeIds?.length === plan.nodeCount, 'WebView Web-native rendered node count drifted');
  requireValue(rendererReceipt.webViewHostOwned === true, 'WebView Web-native portal ownership drifted');
  return {
    status: 'OK',
    schemaVersion: RECEIPT_SCHEMA,
    profileId: plan.profileId,
    targetId: plan.targetId,
    hostProfile: plan.hostProfile,
    rendererBackend: plan.rendererBackend,
    carrier: plan.carrier,
    registryId: plan.registryId,
    modelRevision: plan.modelRevision,
    nodeCount: plan.nodeCount,
    optimizedUiNodeCount: plan.optimizedUiNodeCount,
    hostPortalCount: plan.hostPortalCount,
    portals: plan.portals,
    renderStrategy: rendererReceipt.renderStrategy,
    rendererOwnsControllers: false,
    rendererOwnsEffects: false,
    sourceWorkersEmbeddedInPresentation: false,
    deviceAcceptanceRequired: true,
  };
}
return { mapWebViewWebNativeTarget, verifyWebViewWebNativeRendering };
})();

const { resolveWebsiteRuntimeTarget, websiteRuntimeActionReceipt, bindWebsiteRuntimeActions } = (() => {
const MODEL_SCHEMA = 'asrelease-render-model/v1';
const RESOLUTION_SCHEMA = 'asrelease-next-website-runtime-target-resolution/v1';
const ACTION_RECEIPT_SCHEMA = 'asrelease-next-website-runtime-action-receipt/v1';
const NODE_ID = /^[a-z0-9][a-z0-9.-]{1,127}$/;
const REVISION = /^[a-f0-9]{64}$/;

const ACCESSIBILITY_ROLES = Object.freeze({
  'w2a.screen': 'screen',
  'w2a.app-bar': 'heading',
  'w2a.navigation-tabs': 'navigation',
  'w2a.notice': 'status',
  'w2a.action-card': 'button',
  'w2a.hero': 'heading',
  'w2a.navigation-chip': 'button',
  'w2a.content-section': 'group',
  'w2a.media-card': 'article',
  'w2a.event-card': 'article',
  'w2a.article-row': 'article',
  'w2a.bottom-navigation': 'navigation',
  'w2a.webview-route': 'group',
});

function requireValue(condition, message) {
  if (!condition) throw new Error(message);
}

function pagesInLookupOrder(content, currentPage) {
  return [currentPage, ...(content.pages || []).filter((page) => page !== currentPage)];
}

function findSection(content, currentPage, sectionId) {
  for (const page of pagesInLookupOrder(content, currentPage)) {
    const section = (page.sections || []).find((candidate) => candidate.id === sectionId);
    if (section) return section;
  }
  return null;
}

function findItem(content, currentPage, itemId) {
  for (const page of pagesInLookupOrder(content, currentPage)) {
    for (const section of page.sections || []) {
      const item = (section.items || []).find((candidate) => candidate.id === itemId);
      if (item) return item;
    }
  }
  return null;
}

function splitBinding(binding, prefix) {
  const separator = binding.lastIndexOf('.');
  if (!binding.startsWith(prefix) || separator <= prefix.length) return null;
  return { id: binding.slice(prefix.length, separator), field: binding.slice(separator + 1) };
}

function resolveBinding(binding, context) {
  requireValue(typeof binding === 'string' && binding, 'Website Runtime binding must be a non-empty string');
  if (binding === 'site.title') return context.content.title;
  if (binding === 'runtime.currentUrl') return context.currentUrl;
  if (binding.startsWith('item.')) {
    requireValue(context.item, `Website Runtime item binding has no collection context: ${binding}`);
    return context.item[binding.slice(5)];
  }
  const pageBinding = splitBinding(binding, 'page:');
  if (pageBinding) {
    const page = (context.content.pages || []).find((candidate) => candidate.id === pageBinding.id);
    requireValue(page, `Website Runtime page binding is unresolved: ${binding}`);
    return page[pageBinding.field];
  }
  const sectionBinding = splitBinding(binding, 'section:');
  if (sectionBinding) {
    const section = findSection(context.content, context.page, sectionBinding.id);
    requireValue(section, `Website Runtime section binding is unresolved: ${binding}`);
    return section[sectionBinding.field];
  }
  const itemBinding = splitBinding(binding, 'item:');
  if (itemBinding) {
    const item = findItem(context.content, context.page, itemBinding.id);
    requireValue(item, `Website Runtime item binding is unresolved: ${binding}`);
    return item[itemBinding.field];
  }
  throw new Error(`Website Runtime binding kind is unsupported: ${binding}`);
}

function scalarProp(value, label) {
  if (value === null || ['string', 'number', 'boolean'].includes(typeof value)) return value;
  if (Array.isArray(value) && value.every((item) =>
    item === null || ['string', 'number', 'boolean'].includes(typeof item))) {
    return JSON.stringify(value);
  }
  throw new Error(`Website Runtime prop is not scalar: ${label}`);
}

function normalizeProps(props, nodeId) {
  if (!props) return undefined;
  const normalized = Object.fromEntries(Object.entries(props)
    .map(([name, value]) => [name, scalarProp(value, `${nodeId}.${name}`)]));
  return Object.keys(normalized).length ? normalized : undefined;
}

function normalizeAction(action, context) {
  if (action === undefined || action === null) return undefined;
  requireValue(action && typeof action === 'object' && !Array.isArray(action), 'Website Runtime action must be an object');
  let normalized;
  if (action.type === 'nativePage') {
    requireValue((context.projection.screens || []).some((screen) => screen.routeId === action.target),
      `Website Runtime native route is unresolved: ${action.target}`);
    normalized = { kind: 'native-route', target: `native://${action.target}` };
  } else if (action.type === 'webUrl') {
    requireValue(typeof action.url === 'string' && action.url.startsWith('https://'),
      `Website Runtime Web route must use HTTPS: ${action.url}`);
    normalized = { kind: 'web-route', target: action.url };
  } else if (action.type === 'webOperation') {
    requireValue((context.content.webOperations || []).some((operation) => operation.id === action.operationId),
      `Website Runtime operation is unresolved: ${action.operationId}`);
    normalized = { kind: 'host-capability', target: action.operationId };
  } else {
    throw new Error(`Website Runtime action type is unsupported: ${action.type}`);
  }
  context.actionCounts[normalized.kind] += 1;
  return normalized;
}

function collectionLabel(binding, context) {
  const sectionBinding = splitBinding(binding || '', 'section:');
  if (!sectionBinding) return '';
  return String(findSection(context.content, context.page, sectionBinding.id)?.title || '');
}

function accessibility(node, content, collectionBinding, context) {
  const role = ACCESSIBILITY_ROLES[node.component] || 'group';
  const label = String(content.title || content.subtitle || content.summary ||
    collectionLabel(collectionBinding, context) ||
    (node.component === 'w2a.screen' ? context.page.title : '') ||
    `${node.component} ${context.page.title}`).trim();
  requireValue(label, `Website Runtime accessibility label is empty: ${node.id}`);
  return { role, label };
}

function runtimeNodeId(nodeId, item) {
  const resolved = item ? `${nodeId}.${item.id}` : nodeId;
  requireValue(NODE_ID.test(resolved), `Website Runtime node ID is invalid: ${resolved}`);
  return resolved;
}

function resolveNode(source, context) {
  requireValue(source && typeof source === 'object' && !Array.isArray(source), 'Website Runtime component node must be an object');
  const id = runtimeNodeId(source.id, context.item);
  requireValue(!context.nodeIds.has(id), `Website Runtime node ID is duplicated: ${id}`);
  context.nodeIds.add(id);
  const node = {
    id,
    component: source.component,
    version: source.version,
    variant: source.variant,
  };
  const props = normalizeProps(source.props, id);
  if (props) node.props = props;

  const content = {};
  let action;
  let collection = null;
  let collectionBinding = '';
  for (const [name, binding] of Object.entries(source.bindings || {})) {
    const value = resolveBinding(binding, context);
    context.stats.resolvedBindings += 1;
    if (name === 'items') {
      requireValue(Array.isArray(value), `Website Runtime collection binding is not an array: ${binding}`);
      collection = value;
      collectionBinding = binding;
      continue;
    }
    if (name === 'action') {
      action = normalizeAction(value, context);
      continue;
    }
    if (name === 'secondaryAction') continue;
    if (value !== undefined && value !== null && value !== '') content[name] = scalarProp(value, `${id}.${name}`);
  }
  if (Object.keys(content).length) node.content = content;
  if (action) node.action = action;
  node.accessibility = accessibility(node, content, collectionBinding, context);

  const slots = {};
  for (const [slotName, child] of Object.entries(source.slots || {})) {
    if (slotName === 'item' && collection) {
      requireValue(!Array.isArray(child), `Website Runtime collection template must be one node: ${id}.${slotName}`);
      slots[slotName] = collection.map((item) => {
        requireValue(item && typeof item.id === 'string', `Website Runtime collection item is missing identity: ${collectionBinding}`);
        context.stats.expandedItems += 1;
        return resolveNode(child, { ...context, item });
      });
      context.collectionBindings.push({ nodeId: id, binding: collectionBinding, items: collection.length });
    } else {
      slots[slotName] = Array.isArray(child)
        ? child.map((item) => resolveNode(item, { ...context, item: null }))
        : resolveNode(child, { ...context, item: null });
    }
  }
  if (collection && !Object.prototype.hasOwnProperty.call(slots, 'item')) {
    throw new Error(`Website Runtime collection has no item slot: ${id}`);
  }
  if (Object.keys(slots).length) node.slots = slots;
  return node;
}

function resolvedTheme(theme) {
  const colors = theme?.colors || {};
  const result = {
    surface: colors.surfaceDefault,
    surfaceRaised: colors.surfaceCard,
    text: colors.textPrimary,
    textMuted: colors.textSecondary,
    accent: colors.brandPrimary,
    accentStrong: colors.brandAccent,
  };
  for (const [name, value] of Object.entries(result)) {
    requireValue(/^#[0-9a-fA-F]{6}$/.test(String(value || '')), `Website Runtime theme color is invalid: ${name}`);
  }
  return result;
}

function resolveWebsiteRuntimeTarget({
  siteSkill, projection, content, theme, routeId, currentUrl, revision,
  viewportClass = 'mobile-compact',
}) {
  requireValue(siteSkill?.schemaVersion === 'web2atomic-website-skill/v1', 'unsupported Website Skill contract');
  requireValue(projection?.schemaVersion === 'web2atomic-native-projection/v1', 'unsupported Website projection contract');
  requireValue(content?.schemaVersion === 1, 'unsupported Website Runtime content contract');
  requireValue(theme?.schemaVersion === 'web2atomic-design-tokens/v1', 'unsupported Website theme contract');
  requireValue(projection.siteSkillId === siteSkill.id, 'Website Skill and projection identity differ');
  requireValue(projection.rendererApi === '1.0', 'unsupported Website projection Renderer API');
  requireValue(REVISION.test(String(revision || '')), 'Website Runtime revision must be an exact SHA-256');
  requireValue(['mobile-compact', 'mobile-expanded', 'desktop-reference'].includes(viewportClass),
    `Website Runtime viewport class is unsupported: ${viewportClass}`);
  const screen = (projection.screens || []).find((candidate) => candidate.routeId === routeId);
  const page = (content.pages || []).find((candidate) => candidate.id === routeId);
  requireValue(screen, `Website Runtime projection has no route: ${routeId}`);
  requireValue(page, `Website Runtime content has no route: ${routeId}`);
  requireValue((siteSkill.runtimeMigration?.screenIds || []).includes(screen.id),
    `Website Runtime route is not admitted for migration: ${routeId}`);

  const context = {
    siteSkill, projection, content, page, currentUrl, item: null,
    nodeIds: new Set(), collectionBindings: [], stats: { expandedItems: 0, resolvedBindings: 0 },
    actionCounts: { 'native-route': 0, 'web-route': 0, 'host-capability': 0 },
  };
  const model = {
    schemaVersion: MODEL_SCHEMA,
    revision,
    rendererApi: projection.rendererApi,
    viewportClass,
    theme: resolvedTheme(theme),
    root: resolveNode(screen.root, context),
  };
  const receipt = {
    status: 'OK',
    schemaVersion: RESOLUTION_SCHEMA,
    authority: 'website-runtime-host',
    siteSkillId: siteSkill.id,
    siteId: content.siteId,
    screenId: screen.id,
    routeId,
    modelRevision: revision,
    nodeCount: context.nodeIds.size,
    resolvedBindings: context.stats.resolvedBindings,
    expandedItems: context.stats.expandedItems,
    collectionBindings: context.collectionBindings,
    actionCounts: context.actionCounts,
    rendererOwnsEffects: false,
  };
  return { model, receipt };
}

function websiteRuntimeActionReceipt(detail, { siteSkillId, routeId }) {
  const action = detail?.action;
  requireValue(detail?.nodeId && detail?.component && action?.kind && action?.target,
    'Website Runtime action event is incomplete');
  const requestKinds = {
    'native-route': 'route-request',
    'web-route': 'navigation-request',
    'host-capability': 'capability-request',
  };
  requireValue(requestKinds[action.kind], `Website Runtime action kind is unsupported: ${action.kind}`);
  return {
    status: 'REQUESTED',
    schemaVersion: ACTION_RECEIPT_SCHEMA,
    authority: 'website-runtime-host',
    siteSkillId,
    routeId,
    nodeId: detail.nodeId,
    component: detail.component,
    requestKind: requestKinds[action.kind],
    action: { kind: action.kind, target: action.target },
    effectExecuted: false,
  };
}

function bindWebsiteRuntimeActions(target, context, onRequest = () => {}) {
  requireValue(target?.addEventListener && target?.removeEventListener, 'Website Runtime action target is invalid');
  let lastReceipt = null;
  const listener = (event) => {
    lastReceipt = websiteRuntimeActionReceipt(event.detail, context);
    onRequest(lastReceipt);
  };
  target.addEventListener('w2a-action', listener);
  return Object.freeze({
    lastReceipt: () => lastReceipt,
    dispose: () => target.removeEventListener('w2a-action', listener),
  });
}
return { resolveWebsiteRuntimeTarget, websiteRuntimeActionReceipt, bindWebsiteRuntimeActions };
})();

const { resolveWebsiteProfileRuntime, runWebsiteProfileRuntimeCases } = (() => {
const BUNDLE_SCHEMA = 'asrelease-next-website-profile-runtime-bundle/v1';
const RECEIPT_SCHEMA = 'asrelease-next-website-profile-runtime-receipt/v1';

function requireValue(condition, message) {
  if (!condition) throw new Error(message);
}

function profilesFor(bundle, ids) {
  const admitted = new Set(ids || []);
  return bundle.profiles.filter((profile) => admitted.has(profile.identity.profileId));
}

function entryFor(bundle, profileId) {
  return bundle.entries.find((entry) => entry.profileId === profileId);
}

function modelComponents(model) {
  const components = new Set();
  const visit = (node) => {
    if (!node || typeof node !== 'object') return;
    if (typeof node.component === 'string') components.add(node.component);
    for (const value of Object.values(node.slots || {})) {
      for (const child of Array.isArray(value) ? value : [value]) visit(child);
    }
  };
  visit(model?.root);
  return [...components].sort();
}

function resolveWebsiteProfileRuntime({ contract, bundle, runtimeCase }) {
  requireValue(bundle?.schemaVersion === BUNDLE_SCHEMA, 'Website Profile Runtime bundle is unsupported');
  requireValue(Number.isSafeInteger(bundle.bundleGeneration) && bundle.bundleGeneration > 0,
    'Website Profile Runtime bundle generation is invalid');
  requireValue(/^[a-f0-9]{64}$/.test(String(bundle.bundleRevision || '')),
    'Website Profile Runtime bundle revision is invalid');
  const selection = selectWebsiteProfile({
    contract,
    profiles: profilesFor(bundle, runtimeCase.profileIds),
    observation: runtimeCase.observation,
    requestedTarget: runtimeCase.requestedTarget,
    host: bundle.host,
    nowEpochMs: bundle.nowEpochMs,
  });
  if (selection.status === 'NEEDS_PROFILER') {
    return {
      status: 'NEEDS_PROFILER',
      schemaVersion: RECEIPT_SCHEMA,
      bundleId: bundle.bundleId,
      bundleRevision: bundle.bundleRevision,
      selection,
      model: null,
      resolution: null,
      targetPlan: null,
      effectExecuted: false,
    };
  }
  requireValue(selection.status === 'SELECTED', 'Website Profile Runtime selection failed');
  const entry = entryFor(bundle, selection.profileId);
  requireValue(entry, 'Website Profile Runtime selected profile has no entry');
  requireValue(entry.modelRevision === runtimeCase.expectedModelRevision,
    'Website Profile Runtime model revision binding drifted');
  const resolved = resolveWebsiteRuntimeTarget({
    ...entry.inputs,
    routeId: entry.routeId,
    currentUrl: entry.currentUrl,
    viewportClass: entry.viewportClass,
    revision: entry.modelRevision,
  });
  requireValue(resolved.receipt.nodeCount === runtimeCase.expectedNodes,
    'Website Profile Runtime node count drifted');
  const components = modelComponents(resolved.model);
  const webNative = new Set(bundle.host.webNativeComponents || []);
  const arkUi = new Set(bundle.host.arkUiComponents || []);
  const webMissing = components.filter((component) => !webNative.has(component));
  requireValue(webMissing.length === 0,
    `Website Profile Runtime Web-native profile is missing ${webMissing.join(',')}`);
  const arkUiMissing = components.filter((component) => !arkUi.has(component));
  const selectedTarget = selection.selectedTarget === 'native-arkui' && arkUiMissing.length > 0
    ? 'native-webview-web-native' : selection.selectedTarget;
  const targetFallbackReason = selection.selectedTarget === 'native-arkui' && arkUiMissing.length > 0
    ? 'arkui-resolved-model-subset-miss' : (selection.targetFallbackReason || '');
  let targetPlan = null;
  if (selectedTarget === 'native-webview-web-native') {
    targetPlan = mapWebViewWebNativeTarget({
      profile: bundle.webViewProfile,
      model: resolved.model,
      resolutionReceipt: resolved.receipt,
    });
    requireValue(targetPlan.hostPortalCount === runtimeCase.expectedPortalCount,
      'Website Profile Runtime portal count drifted');
  } else {
    requireValue(selectedTarget === 'native-arkui',
      'Website Profile Runtime selected target is unsupported');
  }
  return {
    status: 'PASS',
    schemaVersion: RECEIPT_SCHEMA,
    bundleId: bundle.bundleId,
    bundleRevision: bundle.bundleRevision,
    selection,
    selectedTarget,
    targetFallbackReason,
    modelComponents: components,
    unsupportedModelComponents: selectedTarget === 'native-arkui' ? [] : arkUiMissing,
    model: resolved.model,
    resolution: resolved.receipt,
    targetPlan,
    modelBytes: new TextEncoder().encode(JSON.stringify(resolved.model)).byteLength,
    effectExecuted: false,
  };
}

function runWebsiteProfileRuntimeCases({ contract, bundle }) {
  return bundle.runtimeCases.map((runtimeCase) => ({
    id: runtimeCase.id,
    expected: runtimeCase,
    receipt: resolveWebsiteProfileRuntime({ contract, bundle, runtimeCase }),
  }));
}
return { resolveWebsiteProfileRuntime, runWebsiteProfileRuntimeCases };
})();

const { loadWebsiteProfileWasm } = (() => {
const UUID = /^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/;
const DIGEST = /^[a-f0-9]{64}$/;
const RECEIPT_SCHEMA = 'asrelease-next-website-profile-wasm-load-receipt/v1';

function requireValue(condition, message) {
  if (!condition) throw new Error(message);
}

function positiveInteger(value, label) {
  requireValue(Number.isSafeInteger(value) && value > 0, `${label} is invalid`);
  return value;
}

function exportedFunction(exports, name) {
  const value = exports[name];
  requireValue(typeof value === 'function', `Website Profile Wasm export is missing: ${name}`);
  return value;
}

function canonical(value) {
  if (Array.isArray(value)) return value.map(canonical);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonical(value[key])]));
  }
  return value;
}

function canonicalBytes(value) {
  return new TextEncoder().encode(JSON.stringify(canonical(value)));
}

async function loadWebsiteProfileWasm({
  bytes, contract, websiteSkillUuid, websiteGeneration, profileId, sha256Hex,
}) {
  requireValue(contract?.schemaVersion === 'asrelease-next-website-profile-wasm-contract/v1',
    'Website Profile Wasm contract is unsupported');
  requireValue(bytes instanceof Uint8Array && bytes.length >= 8 &&
    bytes.length <= contract.module.maximumModuleBytes,
  'Website Profile Wasm module size is rejected');
  requireValue(UUID.test(String(websiteSkillUuid || '')), 'Website Skill UUID is invalid');
  positiveInteger(websiteGeneration, 'Website generation');
  requireValue(typeof profileId === 'string' && profileId.length > 0,
    'Website Profile ID is invalid');
  requireValue(typeof sha256Hex === 'function', 'Website Profile Wasm digest adapter is missing');

  const module = await WebAssembly.compile(bytes);
  requireValue(contract.module.importsAllowed === false && WebAssembly.Module.imports(module).length === 0,
    'Website Profile Wasm imports are forbidden');
  const expectedExports = Object.values(contract.module.exports).sort();
  const actualExports = WebAssembly.Module.exports(module).map((item) => item.name).sort();
  requireValue(JSON.stringify(actualExports) === JSON.stringify(expectedExports),
    'Website Profile Wasm export inventory drifted');
  const instance = await WebAssembly.instantiate(module, {});
  const names = contract.module.exports;
  requireValue(instance.exports[names.memory] instanceof WebAssembly.Memory,
    'Website Profile Wasm memory export is missing');
  const abiVersion = exportedFunction(instance.exports, names.abiVersion)();
  const pointer = exportedFunction(instance.exports, names.payloadPointer)();
  const length = exportedFunction(instance.exports, names.payloadLength)();
  const exportedProfileGeneration = exportedFunction(instance.exports, names.profileGeneration)();
  const exportedWebsiteGeneration = exportedFunction(instance.exports, names.websiteGeneration)();
  requireValue(abiVersion === contract.module.abiVersion, 'Website Profile Wasm ABI is incompatible');
  requireValue(pointer === contract.module.payloadOffset && Number.isSafeInteger(length) && length > 1 &&
    length <= contract.module.maximumPayloadBytes && pointer + length <= instance.exports[names.memory].buffer.byteLength,
  'Website Profile Wasm payload bounds are rejected');
  requireValue(exportedWebsiteGeneration === websiteGeneration,
    'Website Profile Wasm Website generation drifted');

  const payloadBytes = new Uint8Array(instance.exports[names.memory].buffer, pointer, length).slice();
  let bundle;
  try {
    bundle = JSON.parse(new TextDecoder().decode(payloadBytes));
  } catch {
    throw new Error('Website Profile Wasm payload JSON is malformed');
  }
  requireValue(bundle?.schemaVersion === contract.payload.schemaVersion,
    'Website Profile Wasm payload schema is unsupported');
  requireValue(bundle.websiteSkillUuid === websiteSkillUuid &&
    bundle.websiteGeneration === websiteGeneration && bundle.compiledProfileId === profileId,
  'Website Profile Wasm payload identity drifted');
  requireValue(Number.isSafeInteger(bundle.bundleGeneration) && bundle.bundleGeneration > 0 &&
    bundle.bundleGeneration === exportedProfileGeneration,
  'Website Profile Wasm Profile generation drifted');
  requireValue(DIGEST.test(String(bundle.bundleRevision || '')),
    'Website Profile Wasm bundle revision is invalid');
  const revisionInput = structuredClone(bundle);
  delete revisionInput.bundleRevision;
  requireValue(await sha256Hex(canonicalBytes(revisionInput)) === bundle.bundleRevision,
    'Website Profile Wasm bundle revision drifted');
  requireValue(Array.isArray(bundle.profiles) && bundle.profiles.length === 1 &&
    bundle.profiles[0]?.identity?.profileId === profileId &&
    bundle.profiles[0]?.identity?.generation === exportedProfileGeneration,
  'Website Profile Wasm profile inventory drifted');
  requireValue(bundle.profiles[0]?.source?.mode === contract.payload.sourceMode &&
    bundle.profiles[0]?.integrity?.authority === contract.payload.integrityAuthority &&
    DIGEST.test(String(bundle.profiles[0]?.identity?.revision || '')),
  'Website Profile Wasm release authority drifted');
  const semanticProfile = structuredClone(bundle.profiles[0]);
  const expectedProfileRevision = semanticProfile.identity.revision;
  delete semanticProfile.identity.revision;
  delete semanticProfile.source;
  delete semanticProfile.integrity;
  requireValue(await sha256Hex(canonicalBytes(semanticProfile)) === expectedProfileRevision &&
    bundle.profiles[0].integrity.digest === expectedProfileRevision,
  'Website Profile Wasm semantic profile revision drifted');
  requireValue(Array.isArray(bundle.entries) && bundle.entries.length === 1 &&
    bundle.entries[0]?.profileId === profileId,
  'Website Profile Wasm runtime entry inventory drifted');
  requireValue(bundle.entries[0]?.inputs?.siteSkill?.websiteSkillUuid === websiteSkillUuid &&
    !Object.hasOwn(bundle.entries[0].inputs.siteSkill, 'entrypoints'),
  'Website Profile Wasm Website Skill binding drifted');
  requireValue(Array.isArray(bundle.runtimeCases) && bundle.runtimeCases.length > 0 &&
    bundle.runtimeCases.every((item) => Array.isArray(item.profileIds) &&
      item.profileIds.length === 1 && item.profileIds[0] === profileId),
  'Website Profile Wasm runtime cases escaped the selected profile');

  return {
    bundle,
    payloadBytes,
    receipt: {
      schemaVersion: RECEIPT_SCHEMA,
      status: 'LOADED',
      websiteSkillUuid,
      websiteGeneration,
      profileId,
      profileGeneration: exportedProfileGeneration,
      bundleRevision: bundle.bundleRevision,
      moduleBytes: bytes.length,
      payloadBytes: length,
      imports: 0,
      effectExecuted: false,
    },
  };
}
return { loadWebsiteProfileWasm };
})();

globalThis.__w2aWebsiteRuntimeReceipt = { status: 'waiting-native-host' };

function decodeBase64Bytes(value) {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
  return bytes;
}

function decodeBase64(value) {
  return new TextDecoder().decode(decodeBase64Bytes(value));
}

async function sha256Hex(bytes) {
  const digest = new Uint8Array(await crypto.subtle.digest('SHA-256', bytes));
  return Array.from(digest, (value) => value.toString(16).padStart(2, '0')).join('');
}

function activateBundle(bundle, acquisition, contract, wasmLoad = null) {
  const cases = runWebsiteProfileRuntimeCases({ contract, bundle });
  const primary = cases.find((item) => item.id === 'peterhof-web-native')?.receipt;
  if (primary?.status !== 'PASS' || primary.selectedTarget !== 'native-webview-web-native') {
    throw new Error('profile_runtime_primary_not_ready');
  }
  globalThis.__w2aWebsiteRuntimeReceipt = {
    status: 'PASS',
    schemaVersion: 'asrelease-next-arkweb-website-profile-runtime/v1',
    acquisition,
    wasmLoad,
    bundleId: bundle.bundleId,
    bundleGeneration: bundle.bundleGeneration,
    bundleRevision: bundle.bundleRevision,
    profileId: primary.selection.profileId,
    profileRevision: primary.selection.profileRevision,
    modelRevision: primary.resolution.modelRevision,
    modelBytes: primary.modelBytes,
    nodeCount: primary.resolution.nodeCount,
    hostPortalCount: primary.targetPlan.hostPortalCount,
    selectedTarget: primary.selectedTarget,
    modelComponents: primary.modelComponents,
    cases: cases.map((item) => ({
      id: item.id,
      status: item.receipt.status,
      profileId: item.receipt.selection.profileId || '',
      selectedTarget: item.receipt.selectedTarget || '',
      targetFallbackReason: item.receipt.targetFallbackReason || '',
      unsupportedModelComponents: item.receipt.unsupportedModelComponents || [],
      fallbackSurface: item.receipt.selection.fallbackSurface || '',
      modelRevision: item.receipt.resolution?.modelRevision || '',
      nodeCount: item.receipt.resolution?.nodeCount || 0,
      effectExecuted: item.receipt.effectExecuted,
    })),
    modelJson: JSON.stringify(primary.model),
    effectExecuted: false,
  };
}

globalThis.__w2aWebsiteRuntimeBootstrap = async function bootstrapWebsiteRuntime(
  bundleBase64, acquisitionReceiptJson, contractBase64) {
  try {
    const acquisition = JSON.parse(acquisitionReceiptJson);
    if (acquisition?.schemaVersion !== 'asrelease-next-website-profile-acquisition-receipt/v1' ||
      acquisition.integrityStatus !== 'verified' ||
      !['ACTIVATED', 'UNCHANGED', 'ROLLED_BACK'].includes(acquisition.status)) {
      throw new Error('profile_runtime_unverified_artifact_rejected');
    }
    const bundle = JSON.parse(decodeBase64(bundleBase64));
    const contract = JSON.parse(decodeBase64(contractBase64));
    if (bundle.bundleId !== acquisition.bundleId ||
      bundle.bundleGeneration !== acquisition.generation ||
      bundle.bundleRevision !== acquisition.bundleRevision) {
      throw new Error('profile_runtime_acquisition_binding_mismatch');
    }
    activateBundle(bundle, {
      status: acquisition.status,
      source: acquisition.source,
      generation: acquisition.generation,
      artifactSha256: acquisition.artifactSha256,
      signerKeyId: acquisition.signerKeyId,
      integrityStatus: acquisition.integrityStatus,
      fallbackSource: acquisition.fallbackSource,
      cacheUpdated: acquisition.cacheUpdated,
      effectExecuted: acquisition.effectExecuted,
    }, contract);
  } catch (error) {
    globalThis.__w2aWebsiteRuntimeReceipt = {
      status: 'FAIL',
      error: String(error?.stack || error),
      effectExecuted: false,
    };
  }
  return JSON.stringify(globalThis.__w2aWebsiteRuntimeReceipt);
};

globalThis.__w2aWebsitePlatformRuntimeBootstrap = async function bootstrapPlatformWebsiteRuntime(
  profileWasmBase64, wasmContractBase64, profilerContractBase64, migrationReceiptJson,
  websiteSkillUuid, websiteGeneration, profileId) {
  try {
    const platform = JSON.parse(migrationReceiptJson);
    if (platform?.migration?.schemaVersion !==
        'asrelease-next-website-distribution-migration/v1' ||
        platform.migration.mode !== 'PLATFORM_RELEASE_ACTIVE' ||
        platform?.distribution?.schemaVersion !==
        'asrelease-next-website-distribution-receipt/v1' ||
        platform.distribution.integrityStatus !== 'verified' ||
        !['ACTIVE_ONLINE', 'ACTIVE_CACHE', 'ACTIVE_CACHE_REFRESH_REJECTED', 'UNCHANGED']
          .includes(platform.distribution.status)) {
      throw new Error('profile_runtime_platform_release_rejected');
    }
    const loaded = await loadWebsiteProfileWasm({
      bytes: decodeBase64Bytes(profileWasmBase64),
      contract: JSON.parse(decodeBase64(wasmContractBase64)),
      websiteSkillUuid,
      websiteGeneration,
      profileId,
      sha256Hex,
    });
    activateBundle(loaded.bundle, {
      status: platform.distribution.status,
      source: platform.distribution.sourceId,
      generation: platform.distribution.websiteGeneration,
      artifactSha256: loaded.receipt.bundleRevision,
      signerKeyId: '',
      integrityStatus: platform.distribution.integrityStatus,
      fallbackSource: platform.distribution.fallbackSource,
      cacheUpdated: platform.distribution.cacheUpdated,
      effectExecuted: false,
    }, JSON.parse(decodeBase64(profilerContractBase64)), loaded.receipt);
  } catch (error) {
    globalThis.__w2aWebsiteRuntimeReceipt = {
      status: 'FAIL',
      error: String(error?.stack || error),
      effectExecuted: false,
    };
  }
  return JSON.stringify(globalThis.__w2aWebsiteRuntimeReceipt);
};
})();
